# Generated by Django 4.1.7 on 2023-05-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0002_remove_favouritemodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='favouritemodel',
            name='enabled',
        ),
        migrations.AddField(
            model_name='favouritemodel',
            name='owner',
            field=models.ManyToManyField(blank=True, related_name='favourite_owner', to='soccer.ipmodel'),
        ),
    ]
